name: Sync to GitLab Dev

on:
  push:
    branches:
      - main

jobs:
  sync-to-gitlab:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Push to GitLab Dev Branch
      env:
        GITLAB_PAT: ${{ secrets.GITLAB_PAT }}
      run: |
        # Add GitLab remote
        git remote add gitlab https://oauth2:$GITLAB_PAT@gitlab.presidio.com/amridha/glueetlutils.git
        # Fetch latest changes from GitLab's dev branch
        git fetch gitlab dev || true
        # Force push to the dev branch on GitLab
        git push --force gitlab main:dev
