name: Sync to GitLab Dev

on:
  push:
    branches:
      - main

jobs:
  sync-to-gitlab:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch the entire commit history

    - name: Push to GitLab Dev Branch
      env:
        GITLAB_PAT: ${{ secrets.GITLAB_PAT }}
      run: |
        # Add GitLab remote
        git remote add gitlab https://oauth2:$GITLAB_PAT@gitlab.presidio.com/amridha/glueetlutils.git
        # Fetch full history of the dev branch
        git fetch gitlab dev || true
        # Push GitHub main branch to GitLab dev branch, overwriting if necessary
        git push --force gitlab main:dev
