name: Build and Upload to AWS CodeArtifact

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        pip install setuptools wheel twine boto3

    - name: Build the Package
      run: |
        python setup.py sdist bdist_wheel

    - name: Test the Package Build
      run: |
        pip install dist/*.whl

    - name: Authenticate with AWS CodeArtifact
      run: |
        DOMAIN=${{ secrets.CODEARTIFACT_DOMAIN }}
        ACCOUNT_ID=${{ secrets.CODEARTIFACT_ACCOUNT_ID }}
        REPO=${{ secrets.CODEARTIFACT_REPO }}
        REGION=${{ secrets.CODEARTIFACT_REGION }}
        CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain $DOMAIN --domain-owner $ACCOUNT_ID --region $REGION --query authorizationToken --output text)
        echo "[distutils]" > ~/.pypirc
        echo "index-servers =" >> ~/.pypirc
        echo "    codeartifact" >> ~/.pypirc
        echo "[codeartifact]" >> ~/.pypirc
        echo "repository: https://$DOMAIN-$ACCOUNT_ID.d.codeartifact.$REGION.amazonaws.com/pypi/$REPO/" >> ~/.pypirc
        echo "username: aws" >> ~/.pypirc
        echo "password: $CODEARTIFACT_AUTH_TOKEN" >> ~/.pypirc

    - name: Upload to AWS CodeArtifact
      run: |
        twine upload --non-interactive dist/*
