name: Build and Upload to AWS CodeArtifact

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        pip install setuptools wheel twine boto3

        - name: Check Version Change
        id: version-check
        run: |
          # Extract the current version from setup.py using regex
          CURRENT_VERSION=$(grep -oP "(?<=version=\")[^\"]+" setup.py)
          
          # Compare with the previous version in the main branch
          git fetch --depth=1 origin main
          PREVIOUS_VERSION=$(git show origin/main:setup.py | grep -oP "(?<=version=\")[^\"]+")
      
          echo "Current Version: $CURRENT_VERSION"
          echo "Previous Version: $PREVIOUS_VERSION"
      
          if [ "$CURRENT_VERSION" = "$PREVIOUS_VERSION" ]; then
            echo "No version change detected. Skipping build and upload."
            echo "version_changed=false" >> $GITHUB_ENV
            exit 0
          else
            echo "Version change detected."
            echo "version_changed=true" >> $GITHUB_ENV
          fi      

    - name: Exit if No Version Change
      if: env.version_changed == 'false'
      run: exit 0

    - name: Build the Package
      run: |
        python setup.py sdist bdist_wheel

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Authenticate with AWS CodeArtifact
      run: |
        TWINE_USERNAME=aws
        TWINE_PASSWORD=$(aws codeartifact get-authorization-token --domain presidio-data --domain-owner 894811220469 --region us-east-1 --query authorizationToken --output text)
        TWINE_REPOSITORY_URL=$(aws codeartifact get-repository-endpoint --domain presidio-data --domain-owner 894811220469 --repository datatransformutils-repo --region us-east-1 --format pypi --query repositoryEndpoint --output text)
        echo "::add-mask::$TWINE_PASSWORD"
        echo "TWINE_USERNAME=$TWINE_USERNAME" >> $GITHUB_ENV
        echo "TWINE_PASSWORD=$TWINE_PASSWORD" >> $GITHUB_ENV
        echo "TWINE_REPOSITORY_URL=$TWINE_REPOSITORY_URL" >> $GITHUB_ENV

    - name: Upload to AWS CodeArtifact
      env:
        TWINE_USERNAME: ${{ env.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ env.TWINE_PASSWORD }}
        TWINE_REPOSITORY_URL: ${{ env.TWINE_REPOSITORY_URL }}
      run: |
        twine upload --repository-url $TWINE_REPOSITORY_URL dist/*
